#!/bin/bash

TARGET_FILE="$1".jl
SCRAPERS=["macalaylibrary"]

if [ $# -eq 0 ]
  then
    for scraper in scrapers; do
		echo "scrape all"
	done
else
	rm "$TARGET_FILE"
	# Scrape scrape scrape
	scrapy crawl "$1" -o "$TARGET_FILE" -t jl
fi